# Modelo SQLAlchemy 2.0 async - DDL corregido PG16 (ver backend/db/schema.sql)
# Fixes: IDENTITY, lat/lon DECIMAL(10,7), indice_confianza 0-100, tabla audit, CHECKs, FKs
from sqlalchemy import (
    BigInteger, Boolean, CheckConstraint, Column, DateTime, ForeignKey, Integer, SmallInteger,
    String, Text, Numeric, Table, UniqueConstraint, Index, func, text as sa_text
)
import sqlalchemy as sa
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column, relationship
from datetime import datetime, timezone

class Base(DeclarativeBase):
    pass

# ---------------------------------------------------------------------------
# Ciudades
# ---------------------------------------------------------------------------
class Ciudad(Base):
    __tablename__ = "ciudades"
    id: Mapped[int] = mapped_column(BigInteger, primary_key=True, autoincrement=True)  # GENERATED BY DEFAULT AS IDENTITY en DDL
    nombre: Mapped[str] = mapped_column(String(100), unique=True, nullable=False)
    departamento: Mapped[str] = mapped_column(String(100), nullable=False)
    activo: Mapped[bool] = mapped_column(Boolean, default=True, nullable=False)

    zonas: Mapped[list["ZonaBarrio"]] = relationship(back_populates="ciudad", cascade="all, delete-orphan")
    campuses: Mapped[list["CampusUniversitario"]] = relationship(back_populates="ciudad")

# ---------------------------------------------------------------------------
# Zonas / Barrios
# ---------------------------------------------------------------------------
class ZonaBarrio(Base):
    __tablename__ = "zonas_barrios"
    __table_args__ = (
        UniqueConstraint("ciudad_id", "nombre", name="uq_zona_ciudad"),
        CheckConstraint("estrato BETWEEN 1 AND 6", name="chk_estrato"),
        Index("idx_zonas_ciudad", "ciudad_id"),
    )
    id: Mapped[int] = mapped_column(BigInteger, primary_key=True, autoincrement=True)
    ciudad_id: Mapped[int] = mapped_column(ForeignKey("ciudades.id", ondelete="CASCADE"), nullable=False)
    nombre: Mapped[str] = mapped_column(String(120), nullable=False)
    estrato: Mapped[int | None] = mapped_column(SmallInteger, nullable=True)

    ciudad: Mapped["Ciudad"] = relationship(back_populates="zonas")

# ---------------------------------------------------------------------------
# Campus Universitarios
# ---------------------------------------------------------------------------
class CampusUniversitario(Base):
    __tablename__ = "campus_universitarios"
    __table_args__ = (
        UniqueConstraint("ciudad_id", "institucion", "nombre_sede", name="uq_campus_ciudad_sede"),
        CheckConstraint("latitud BETWEEN -90 AND 90", name="chk_campus_lat"),
        CheckConstraint("longitud BETWEEN -180 AND 180", name="chk_campus_lon"),
        Index("idx_campus_ciudad", "ciudad_id"),
    )
    id: Mapped[int] = mapped_column(BigInteger, primary_key=True, autoincrement=True)
    ciudad_id: Mapped[int] = mapped_column(ForeignKey("ciudades.id", ondelete="CASCADE"), nullable=False)
    institucion: Mapped[str] = mapped_column(String(150), nullable=False)
    nombre_sede: Mapped[str] = mapped_column(String(150), nullable=False)
    direccion: Mapped[str] = mapped_column(String(200), nullable=False)
    latitud: Mapped[float] = mapped_column(Numeric(10,7), nullable=False)
    longitud: Mapped[float] = mapped_column(Numeric(10,7), nullable=False)
    activo: Mapped[bool] = mapped_column(Boolean, default=True, nullable=False)

    ciudad: Mapped["Ciudad"] = relationship(back_populates="campuses")

# ---------------------------------------------------------------------------
# Usuarios
# ---------------------------------------------------------------------------
class Usuario(Base):
    __tablename__ = "usuarios"
    __table_args__ = (
        CheckConstraint("rol IN ('ARRENDADOR','ADMIN')", name="chk_rol"),
        CheckConstraint("telefono_whatsapp ~ '^\\+?[0-9]{7,20}$'", name="chk_telefono_formato"),
        Index("idx_usuarios_rol", "rol"),
    )
    id: Mapped[int] = mapped_column(BigInteger, primary_key=True, autoincrement=True)
    nombre_completo: Mapped[str] = mapped_column(String(150), nullable=False)
    email: Mapped[str] = mapped_column(String(180), unique=True, nullable=False)
    password_hash: Mapped[str] = mapped_column(String(255), nullable=False)
    telefono_whatsapp: Mapped[str] = mapped_column(String(20), nullable=False)
    rol: Mapped[str] = mapped_column(String(20), nullable=False)  # ARRENDADOR / ADMIN
    telefono_verificado: Mapped[bool] = mapped_column(Boolean, default=False, nullable=False)
    creado_en: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now())

# ---------------------------------------------------------------------------
# Publicaciones (FIX: + latitud, longitud, indice_confianza + relationships)
# ---------------------------------------------------------------------------
class Publicacion(Base):
    __tablename__ = "publicaciones"
    __table_args__ = (
        CheckConstraint("tipo_inmueble IN ('HABITACION_FAMILIAR','HABITACION_INDEPENDIENTE','APARTAESTUDIO','COMPARTIDO')", name="chk_tipo"),
        CheckConstraint("estado IN ('PENDIENTE','ACTIVO','PAUSADO','ARRENDADO','EXPIRADO','RECHAZADO','DESACTIVADO')", name="chk_estado"),
        CheckConstraint("canon_mensual > 0", name="chk_canon"),
        CheckConstraint("deposito_requerido >= 0", name="chk_deposito"),
        CheckConstraint("indice_confianza BETWEEN 0 AND 100", name="chk_confianza"),
        CheckConstraint("latitud BETWEEN -90 AND 90", name="chk_pub_lat"),
        CheckConstraint("longitud BETWEEN -180 AND 180", name="chk_pub_lon"),
        CheckConstraint("char_length(titulo) >= 10", name="chk_titulo_len"),
        CheckConstraint("char_length(descripcion) >= 20", name="chk_desc_len"),
        CheckConstraint("fecha_expiracion > fecha_publicacion", name="chk_expiracion"),
        Index("idx_publicaciones_estado_canon", "estado", "canon_mensual"),
        Index("idx_publicaciones_zona_estado", "zona_barrio_id", "estado"),
        Index("idx_publicaciones_usuario", "usuario_id"),
        Index("idx_publicaciones_vigencia", "fecha_renovacion"),
    )
    id: Mapped[int] = mapped_column(BigInteger, primary_key=True, autoincrement=True)
    usuario_id: Mapped[int] = mapped_column(ForeignKey("usuarios.id", ondelete="CASCADE"), nullable=False)
    zona_barrio_id: Mapped[int] = mapped_column(ForeignKey("zonas_barrios.id", ondelete="RESTRICT"), nullable=False)
    titulo: Mapped[str] = mapped_column(String(150), nullable=False)
    descripcion: Mapped[str] = mapped_column(Text, nullable=False)
    tipo_inmueble: Mapped[str] = mapped_column(String(30), nullable=False)
    canon_mensual: Mapped[float] = mapped_column(Numeric(10,2), nullable=False)
    deposito_requerido: Mapped[float] = mapped_column(Numeric(10,2), default=0, nullable=False)
    incluye_servicios_base: Mapped[bool] = mapped_column(Boolean, default=True, nullable=False)
    reglas_convivencia: Mapped[str | None] = mapped_column(Text, nullable=True)
    direccion_referencial: Mapped[str] = mapped_column(String(200), nullable=False)
    estado: Mapped[str] = mapped_column(String(20), default="PENDIENTE", nullable=False)
    # FIX CRÍTICO
    latitud: Mapped[float | None] = mapped_column(Numeric(10,7), nullable=True)
    longitud: Mapped[float | None] = mapped_column(Numeric(10,7), nullable=True)
    indice_confianza: Mapped[int] = mapped_column(SmallInteger, default=0, nullable=False)
    fecha_publicacion: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now())
    fecha_renovacion: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now())
    fecha_expiracion: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=sa_text("NOW() + INTERVAL '30 days'"))

    # Relationships para evitar N+1 y permitir selectinload (router espera .servicios y .imagenes)
    zona: Mapped["ZonaBarrio"] = relationship(lazy="joined")
    usuario: Mapped["Usuario"] = relationship(lazy="joined")
    servicios: Mapped[list["ServicioCatalogo"]] = relationship(secondary="publicacion_servicios", lazy="selectin")
    imagenes: Mapped[list["ImagenPublicacion"]] = relationship(back_populates="publicacion", cascade="all, delete-orphan", lazy="selectin")
    campus_links: Mapped[list["PublicacionCampus"]] = relationship(back_populates="publicacion", cascade="all, delete-orphan", lazy="selectin")

# ---------------------------------------------------------------------------
# Servicios Catalogo
# ---------------------------------------------------------------------------
class ServicioCatalogo(Base):
    __tablename__ = "servicios_catalogo"
    __table_args__ = (
        UniqueConstraint("nombre", name="uq_servicio_nombre"),
    )
    id: Mapped[int] = mapped_column(BigInteger, primary_key=True, autoincrement=True)
    nombre: Mapped[str] = mapped_column(String(80), nullable=False)
    categoria: Mapped[str] = mapped_column(String(50), nullable=False)  # Básico/Comodidad/Convivencia

# ---------------------------------------------------------------------------
# N:M publicacion_servicios
# ---------------------------------------------------------------------------
class PublicacionServicio(Base):
    __tablename__ = "publicacion_servicios"
    publicacion_id: Mapped[int] = mapped_column(ForeignKey("publicaciones.id", ondelete="CASCADE"), primary_key=True)
    servicio_id: Mapped[int] = mapped_column(ForeignKey("servicios_catalogo.id", ondelete="CASCADE"), primary_key=True)

# ---------------------------------------------------------------------------
# N:M publicacion_campus (distancia precalculada Haversine)
# ---------------------------------------------------------------------------
class PublicacionCampus(Base):
    __tablename__ = "publicacion_campus"
    __table_args__ = (
        CheckConstraint("distancia_geodesica_m >= 0", name="chk_distancia"),
        Index("idx_pubcampus_campus_dist", "campus_id", "distancia_geodesica_m"),
        Index("idx_pubcampus_pub", "publicacion_id"),
    )
    publicacion_id: Mapped[int] = mapped_column(ForeignKey("publicaciones.id", ondelete="CASCADE"), primary_key=True)
    campus_id: Mapped[int] = mapped_column(ForeignKey("campus_universitarios.id", ondelete="CASCADE"), primary_key=True)
    distancia_geodesica_m: Mapped[int] = mapped_column(Integer, nullable=False)

    publicacion: Mapped["Publicacion"] = relationship(back_populates="campus_links")

# ---------------------------------------------------------------------------
# Imagenes
# ---------------------------------------------------------------------------
class ImagenPublicacion(Base):
    __tablename__ = "imagenes_publicacion"
    __table_args__ = (
        UniqueConstraint("publicacion_id", "orden", name="uq_imagen_pub_orden"),
        CheckConstraint("orden > 0", name="chk_orden"),
        Index("idx_imagenes_pub", "publicacion_id"),
    )
    id: Mapped[int] = mapped_column(BigInteger, primary_key=True, autoincrement=True)
    publicacion_id: Mapped[int] = mapped_column(ForeignKey("publicaciones.id", ondelete="CASCADE"), nullable=False)
    url: Mapped[str] = mapped_column(Text, nullable=False)
    orden: Mapped[int] = mapped_column(SmallInteger, nullable=False)

    publicacion: Mapped["Publicacion"] = relationship(back_populates="imagenes")

# ---------------------------------------------------------------------------
# Reportes (FIX estado solo PENDIENTE/DESCARTADO/CONFIRMADO)
# ---------------------------------------------------------------------------
class ReportePublicacion(Base):
    __tablename__ = "reportes_publicacion"
    __table_args__ = (
        CheckConstraint("motivo IN ('POSIBLE_ESTAFA','DATOS_FALSOS','INMUEBLE_ARRENDADO','FOTOS_ENGANOSAS','OTRO')", name="chk_motivo"),
        CheckConstraint("estado IN ('PENDIENTE','DESCARTADO','CONFIRMADO')", name="chk_reporte_estado"),
        Index("idx_reportes_pub_estado", "publicacion_id", "estado"),
    )
    id: Mapped[int] = mapped_column(BigInteger, primary_key=True, autoincrement=True)
    publicacion_id: Mapped[int] = mapped_column(ForeignKey("publicaciones.id", ondelete="CASCADE"), nullable=False)
    usuario_id: Mapped[int | None] = mapped_column(ForeignKey("usuarios.id", ondelete="SET NULL"), nullable=True)
    motivo: Mapped[str] = mapped_column(String(40), nullable=False)
    detalle: Mapped[str | None] = mapped_column(Text, nullable=True)
    estado: Mapped[str] = mapped_column(String(20), default="PENDIENTE", nullable=False)
    fecha_creacion: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now())

# ---------------------------------------------------------------------------
# Audit (FIX tabla faltante) - alineado a schema.sql
# ---------------------------------------------------------------------------
class PublicacionesAudit(Base):
    __tablename__ = "publicaciones_audit"
    __table_args__ = (
        CheckConstraint("evento IN ('CREATED','APPROVED','REJECTED','PAUSED','RESUMED','RENTED','EXPIRED','RENEWED','BLOCKED')", name="chk_evento"),
        Index("idx_audit_pub", "publicacion_id"),
        Index("idx_audit_evento", "evento"),
    )
    id: Mapped[int] = mapped_column(BigInteger, primary_key=True, autoincrement=True)
    publicacion_id: Mapped[int] = mapped_column(ForeignKey("publicaciones.id", ondelete="CASCADE"), nullable=False)
    usuario_id: Mapped[int | None] = mapped_column(ForeignKey("usuarios.id", ondelete="SET NULL"), nullable=True)
    evento: Mapped[str] = mapped_column(String(20), nullable=False)
    detalle: Mapped[str | None] = mapped_column(Text, nullable=True)
    creado_en: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now())
