-- AlojaU 005 admin automatizado (canónico para Supabase SQL Editor).
BEGIN;
CREATE TABLE IF NOT EXISTS system_settings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  clave VARCHAR(80) NOT NULL UNIQUE,
  valor TEXT NOT NULL,
  tipo VARCHAR(20) NOT NULL DEFAULT 'int',
  descripcion TEXT,
  actualizado_en TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
ALTER TABLE publicaciones DROP CONSTRAINT IF EXISTS chk_estado;
-- Legado: en BDs creadas con schema.sql previo el CHECK nació con nombre
-- automático (publicaciones_estado_check) y debe retirarse también.
ALTER TABLE publicaciones DROP CONSTRAINT IF EXISTS publicaciones_estado_check;
ALTER TABLE publicaciones ADD CONSTRAINT chk_estado CHECK (
  estado IN ('PENDIENTE','ACTIVO','PAUSADO','ARRENDADO','EXPIRADO',
             'RECHAZADO','DESACTIVADO','PAUSADO_POR_REPORTE','REVISION_REQUERIDA')
);
INSERT INTO system_settings (clave, valor, tipo, descripcion) VALUES
  ('dias_vigencia_publicacion', '30', 'int', 'Días de vigencia al publicar/renovar'),
  ('max_reportes_para_pausa_automatica', '3', 'int', 'Reportes PENDIENTE/CONFIRMADO que pausan el aviso'),
  ('auto_aprobar_arrendadores_verificados', 'false', 'bool', 'Si true, PENDIENTE de verificados pasa a ACTIVO sin cola')
ON CONFLICT (clave) DO NOTHING;
COMMIT;
