-- AlojaU - Schema corregido PostgreSQL 16 - Sprint 1
-- Fixes: lat/lng + indice_confianza + audit + IDENTITY + índices NFR
BEGIN;

-- Extensiones
CREATE EXTENSION IF NOT EXISTS pgcrypto;
-- Oleada 2: búsqueda por texto (FTS español + trigramas). Ver alembic 003_busqueda_fts.
CREATE EXTENSION IF NOT EXISTS pg_trgm;
CREATE EXTENSION IF NOT EXISTS unaccent;

-- 1. Ciudades
CREATE TABLE IF NOT EXISTS ciudades (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre VARCHAR(100) NOT NULL UNIQUE,
  departamento VARCHAR(100) NOT NULL,
  activo BOOLEAN NOT NULL DEFAULT TRUE
);

-- 2. Zonas/Barrios
CREATE TABLE IF NOT EXISTS zonas_barrios (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ciudad_id BIGINT NOT NULL REFERENCES ciudades(id) ON DELETE CASCADE,
  nombre VARCHAR(120) NOT NULL,
  estrato SMALLINT CHECK (estrato BETWEEN 1 AND 6),
  UNIQUE(ciudad_id, nombre)
);
CREATE INDEX IF NOT EXISTS idx_zonas_ciudad ON zonas_barrios(ciudad_id);

-- 3. Campus universitarios + 004 POIs (lugares de interés por categoría)
CREATE TABLE IF NOT EXISTS campus_universitarios (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ciudad_id BIGINT NOT NULL REFERENCES ciudades(id) ON DELETE CASCADE,
  institucion VARCHAR(150) NOT NULL,
  nombre_sede VARCHAR(150) NOT NULL,
  direccion VARCHAR(200) NOT NULL,
  latitud DECIMAL(10,7) NOT NULL CHECK (latitud BETWEEN -90 AND 90),
  longitud DECIMAL(10,7) NOT NULL CHECK (longitud BETWEEN -180 AND 180),
  categoria VARCHAR(50) NOT NULL DEFAULT 'UNIVERSIDAD'
    CHECK (categoria IN ('UNIVERSIDAD','CENTRO_COMERCIAL','SALUD','TRANSPORTE','OTRO')),
  activo BOOLEAN NOT NULL DEFAULT TRUE,
  UNIQUE(institucion, nombre_sede)
);
CREATE INDEX IF NOT EXISTS idx_campus_ciudad ON campus_universitarios(ciudad_id);
CREATE INDEX IF NOT EXISTS idx_campus_ciudad_categoria ON campus_universitarios(ciudad_id, categoria);

-- 4. Usuarios (v13: ESTUDIANTE base + ARRENDADOR + ADMIN + futuros roles)
CREATE TABLE IF NOT EXISTS usuarios (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre_completo VARCHAR(150) NOT NULL,
  email VARCHAR(180) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  telefono_whatsapp VARCHAR(20),  -- v13.2: opcional (NULL = sin vincular; se exige al publicar)
  rol VARCHAR(20) NOT NULL DEFAULT 'ESTUDIANTE' CHECK (rol IN ('ESTUDIANTE','ARRENDADOR','ADMIN','MODERADOR_CAMPUS','AUDITOR_LEGAL')),
  telefono_verificado BOOLEAN NOT NULL DEFAULT FALSE,
  creado_en TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  auth_provider VARCHAR(30) NOT NULL DEFAULT 'password',
  supabase_id VARCHAR(64) UNIQUE,
  email_verificado BOOLEAN NOT NULL DEFAULT FALSE,
  acepto_tratamiento_datos BOOLEAN NOT NULL DEFAULT FALSE,
  fecha_consentimiento TIMESTAMPTZ,
  ip_consentimiento VARCHAR(45),
  version_politica VARCHAR(40),
  eliminado_en TIMESTAMPTZ,  -- v13.1 soft-delete (NULL = activa; fecha = gracia 30d)
  bio VARCHAR(500),  -- v13.2 presentación opcional
  foto_perfil_url VARCHAR(500),  -- v13.2 avatar (Google picture, solo https)
  preferencias JSONB NOT NULL DEFAULT '{}'  -- v13.2 extensible (filtros.*, roomie.*, notis.*)
);
CREATE INDEX IF NOT EXISTS idx_usuarios_rol ON usuarios(rol);
CREATE INDEX IF NOT EXISTS idx_usuarios_eliminado ON usuarios(eliminado_en);

-- v13 Enterprise Auth: rate-limit persistente, OTP, recovery y sesiones.
CREATE TABLE IF NOT EXISTS rate_limit_attempts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  clave VARCHAR(180) NOT NULL,
  exito BOOLEAN NOT NULL DEFAULT FALSE,
  creado_en TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_ratelimit_clave_creado ON rate_limit_attempts(clave, creado_en);

CREATE TABLE IF NOT EXISTS otp_codes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email VARCHAR(180) NOT NULL,
  codigo_hash VARCHAR(255) NOT NULL,
  proposito VARCHAR(30) NOT NULL DEFAULT 'email_verify',
  consumido BOOLEAN NOT NULL DEFAULT FALSE,
  expira_en TIMESTAMPTZ NOT NULL,
  creado_en TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_otp_email_creado ON otp_codes(email, creado_en);

CREATE TABLE IF NOT EXISTS password_resets (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email VARCHAR(180) NOT NULL,
  token_hash VARCHAR(255) NOT NULL UNIQUE,
  consumido BOOLEAN NOT NULL DEFAULT FALSE,
  expira_en TIMESTAMPTZ NOT NULL,
  creado_en TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_pwreset_email_creado ON password_resets(email, creado_en);

CREATE TABLE IF NOT EXISTS sesiones (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  usuario_id BIGINT NOT NULL REFERENCES usuarios(id) ON DELETE CASCADE,
  jti VARCHAR(64) NOT NULL UNIQUE,
  ip VARCHAR(45),
  user_agent VARCHAR(255),
  revocado BOOLEAN NOT NULL DEFAULT FALSE,
  creado_en TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  revocado_en TIMESTAMPTZ
);
CREATE INDEX IF NOT EXISTS idx_sesiones_usuario ON sesiones(usuario_id);

-- v15.2 dedup diaria de vistas (marca = SHA256 IP+día, nunca IP en claro).
CREATE TABLE IF NOT EXISTS vistas_dedup (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  publicacion_id BIGINT NOT NULL,
  marca VARCHAR(64) NOT NULL,
  dia VARCHAR(10) NOT NULL,
  creado_en TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT uq_vista_pub_marca UNIQUE (publicacion_id, marca)
);
CREATE INDEX IF NOT EXISTS idx_vistas_dedup_dia ON vistas_dedup(dia);

-- 5. Servicios catálogo
CREATE TABLE IF NOT EXISTS servicios_catalogo (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre VARCHAR(80) NOT NULL UNIQUE,
  categoria VARCHAR(50) NOT NULL
);

-- 6. Publicaciones (oferta central) - FIX lat/lng + indice_confianza
CREATE TABLE IF NOT EXISTS publicaciones (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  usuario_id BIGINT NOT NULL REFERENCES usuarios(id) ON DELETE CASCADE,
  zona_barrio_id BIGINT REFERENCES zonas_barrios(id),  -- 006: NULL (zona del catálogo OPCIONAL: o zona o barrio libre; lo valida Pydantic)
  barrio_texto VARCHAR(120),  -- 006 flexi-barrios (barrio personalizado cuando no hay zona del catálogo)
  titulo VARCHAR(150) NOT NULL CHECK (char_length(titulo) >= 10),
  descripcion TEXT NOT NULL CHECK (char_length(descripcion) >= 20),
  tipo_inmueble VARCHAR(30) NOT NULL CHECK (tipo_inmueble IN ('HABITACION_FAMILIAR','HABITACION_INDEPENDIENTE','APARTAESTUDIO','COMPARTIDO')),
  canon_mensual DECIMAL(10,2) NOT NULL CHECK (canon_mensual > 0),
  deposito_requerido DECIMAL(10,2) NOT NULL DEFAULT 0 CHECK (deposito_requerido >= 0),
  incluye_servicios_base BOOLEAN NOT NULL DEFAULT TRUE,
  reglas_convivencia TEXT NOT NULL CHECK (char_length(reglas_convivencia) >= 10),
  direccion_referencial VARCHAR(200) NOT NULL,
  latitud DECIMAL(10,7) CHECK (latitud BETWEEN -90 AND 90),
  longitud DECIMAL(10,7) CHECK (longitud BETWEEN -180 AND 180),
  estado VARCHAR(20) NOT NULL DEFAULT 'PENDIENTE' CHECK (estado IN ('PENDIENTE','ACTIVO','PAUSADO','ARRENDADO','EXPIRADO','RECHAZADO','DESACTIVADO','PAUSADO_POR_REPORTE','REVISION_REQUERIDA')),  -- 005: 9 estados (ver chk_estado en modelos)
  indice_confianza SMALLINT NOT NULL DEFAULT 0 CHECK (indice_confianza BETWEEN 0 AND 100),
  vistas INTEGER NOT NULL DEFAULT 0,  -- v15.2 métrica (dedup diaria por IP)
  fecha_publicacion TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  fecha_renovacion TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  fecha_expiracion TIMESTAMPTZ NOT NULL DEFAULT (NOW() + INTERVAL '30 days')
);
CREATE INDEX IF NOT EXISTS idx_publicaciones_estado_canon ON publicaciones(estado, canon_mensual);
CREATE INDEX IF NOT EXISTS idx_publicaciones_activo ON publicaciones(estado) WHERE estado='ACTIVO';
-- OLA3/M6: alineación con modelos (antes solo existían los 2 de arriba)
CREATE INDEX IF NOT EXISTS idx_publicaciones_zona_estado ON publicaciones(zona_barrio_id, estado);
CREATE INDEX IF NOT EXISTS idx_publicaciones_usuario ON publicaciones(usuario_id);
CREATE INDEX IF NOT EXISTS idx_publicaciones_vigencia ON publicaciones(fecha_renovacion);
-- Oleada 2 (FTS + trigramas, ver alembic 003_busqueda_fts):
CREATE INDEX IF NOT EXISTS idx_publicaciones_fts ON publicaciones USING gin(to_tsvector('spanish', coalesce(titulo, '') || ' ' || coalesce(descripcion, '')));
CREATE INDEX IF NOT EXISTS idx_publicaciones_trgm ON publicaciones USING gin(titulo gin_trgm_ops);

-- 6b. Trigger distancias + system_settings (005_admin_automation / 004 POIs).
-- Copia fiel de backend/db/migrations/005_fix_estado_and_campus.sql §§3-4 para
-- que una BD creada SOLO desde schema.sql (caso CI) quede igual que una
-- migrada: sin esto el seed falla (estados) y faltan distancias/settings.
CREATE OR REPLACE FUNCTION trg_fn_publicacion_recalcular_distancias()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  IF NEW.latitud IS NULL OR NEW.longitud IS NULL THEN
    UPDATE publicacion_campus
       SET distancia_geodesica_m = NULL
     WHERE publicacion_id = NEW.id;
    RETURN NEW;
  END IF;
  INSERT INTO publicacion_campus (publicacion_id, campus_id, distancia_geodesica_m)
  SELECT NEW.id, c.id,
         haversine_m(NEW.latitud, NEW.longitud, c.latitud, c.longitud)
    FROM campus_universitarios c
    JOIN zonas_barrios z ON z.ciudad_id = c.ciudad_id
    JOIN publicaciones p ON p.id = NEW.id AND p.zona_barrio_id = z.id
   WHERE c.activo = TRUE
  ON CONFLICT (publicacion_id, campus_id)
  DO UPDATE SET distancia_geodesica_m = EXCLUDED.distancia_geodesica_m;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_publicacion_recalcular_distancias ON publicaciones;
CREATE TRIGGER trg_publicacion_recalcular_distancias
AFTER INSERT OR UPDATE OF latitud, longitud ON publicaciones
FOR EACH ROW EXECUTE FUNCTION trg_fn_publicacion_recalcular_distancias();

CREATE TABLE IF NOT EXISTS system_settings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  clave VARCHAR(80) NOT NULL UNIQUE,
  valor TEXT NOT NULL,
  tipo VARCHAR(20) NOT NULL DEFAULT 'int',
  descripcion TEXT,
  actualizado_en TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

INSERT INTO system_settings (clave, valor, tipo, descripcion) VALUES
  ('dias_vigencia_publicacion', '30', 'int', 'Días de vigencia al publicar/renovar'),
  ('max_reportes_para_pausa_automatica', '3', 'int', 'Reportes PENDIENTE/CONFIRMADO que pausan el aviso'),
  ('auto_aprobar_arrendadores_verificados', 'false', 'bool', 'Si true, PENDIENTE de verificados pasa a ACTIVO sin cola')
ON CONFLICT (clave) DO NOTHING;

-- 7. Publicacion - Servicios (N-N)
CREATE TABLE IF NOT EXISTS publicacion_servicios (
  publicacion_id BIGINT NOT NULL REFERENCES publicaciones(id) ON DELETE CASCADE,
  servicio_id BIGINT NOT NULL REFERENCES servicios_catalogo(id) ON DELETE CASCADE,
  PRIMARY KEY (publicacion_id, servicio_id)
);

-- 8. Publicacion - Campus (N-N) con distancia Haversine precalculada
-- B0-5: NULL cuando pub sin coords (no 0). CHECK pasa NULL (solo valida >=0 si no nulo).
CREATE TABLE IF NOT EXISTS publicacion_campus (
  publicacion_id BIGINT NOT NULL REFERENCES publicaciones(id) ON DELETE CASCADE,
  campus_id BIGINT NOT NULL REFERENCES campus_universitarios(id) ON DELETE CASCADE,
  distancia_geodesica_m INTEGER NULL CHECK (distancia_geodesica_m >= 0),
  PRIMARY KEY (publicacion_id, campus_id)
);
CREATE INDEX IF NOT EXISTS idx_pubcampus_campus_dist ON publicacion_campus(campus_id, distancia_geodesica_m);
CREATE INDEX IF NOT EXISTS idx_pubcampus_pub ON publicacion_campus(publicacion_id);

-- 9. Imágenes
CREATE TABLE IF NOT EXISTS imagenes_publicacion (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  publicacion_id BIGINT NOT NULL REFERENCES publicaciones(id) ON DELETE CASCADE,
  url TEXT NOT NULL,
  orden SMALLINT NOT NULL CHECK (orden > 0),
  UNIQUE(publicacion_id, orden)
);
CREATE INDEX IF NOT EXISTS idx_imagenes_pub ON imagenes_publicacion(publicacion_id);

-- 10. Reportes (FIX estado PENDIENTE/DESCARTADO/CONFIRMADO, nunca ACTIVO)
CREATE TABLE IF NOT EXISTS reportes_publicacion (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  publicacion_id BIGINT NOT NULL REFERENCES publicaciones(id) ON DELETE CASCADE,
  usuario_id BIGINT REFERENCES usuarios(id) ON DELETE SET NULL,
  motivo VARCHAR(40) NOT NULL,
  detalle TEXT,
  estado VARCHAR(20) NOT NULL DEFAULT 'PENDIENTE' CHECK (estado IN ('PENDIENTE','DESCARTADO','CONFIRMADO')),
  fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_reportes_pub_estado ON reportes_publicacion(publicacion_id, estado);
CREATE INDEX IF NOT EXISTS idx_reportes_usuario ON reportes_publicacion(usuario_id);

-- 11. Auditoría máquina estados (faltante en doc original)
CREATE TABLE IF NOT EXISTS publicaciones_audit (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  publicacion_id BIGINT REFERENCES publicaciones(id) ON DELETE CASCADE,
  usuario_id BIGINT REFERENCES usuarios(id) ON DELETE SET NULL,
  evento VARCHAR(20) NOT NULL CHECK (evento IN ('CREATED','APPROVED','REJECTED','PAUSED','RESUMED','RENTED','EXPIRED','RENEWED','BLOCKED','SETTINGS','CUENTA_DELETE')),
  detalle TEXT,
  creado_en TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_audit_pub ON publicaciones_audit(publicacion_id, creado_en);
-- OLA3/M6: alineación con modelos + FK usuario sin índice
CREATE INDEX IF NOT EXISTS idx_audit_evento ON publicaciones_audit(evento);
CREATE INDEX IF NOT EXISTS idx_audit_usuario ON publicaciones_audit(usuario_id);

-- 12. Función Haversine (p26) - IMMUTABLE para índices
CREATE OR REPLACE FUNCTION haversine_m(lat1 DOUBLE PRECISION, lon1 DOUBLE PRECISION, lat2 DOUBLE PRECISION, lon2 DOUBLE PRECISION)
RETURNS INTEGER LANGUAGE plpgsql IMMUTABLE STRICT AS $$
DECLARE
  R CONSTANT DOUBLE PRECISION := 6371000;
  dlat DOUBLE PRECISION := radians(lat2-lat1);
  dlon DOUBLE PRECISION := radians(lon2-lon1);
  a DOUBLE PRECISION;
BEGIN
  a := sin(dlat/2)^2 + cos(radians(lat1))*cos(radians(lat2))*sin(dlon/2)^2;
  a := LEAST(1, GREATEST(0, a));
  RETURN (2*R*asin(sqrt(a)))::INTEGER;
END;
$$;

COMMIT;
