-- AlojaU - Schema corregido PostgreSQL 16 - Sprint 1
-- Fixes: lat/lng + indice_confianza + audit + IDENTITY + índices NFR
BEGIN;

-- Extensiones
CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- 1. Ciudades
CREATE TABLE IF NOT EXISTS ciudades (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre VARCHAR(100) NOT NULL UNIQUE,
  departamento VARCHAR(100) NOT NULL,
  activo BOOLEAN NOT NULL DEFAULT TRUE
);

-- 2. Zonas/Barrios
CREATE TABLE IF NOT EXISTS zonas_barrios (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ciudad_id BIGINT NOT NULL REFERENCES ciudades(id),
  nombre VARCHAR(120) NOT NULL,
  estrato SMALLINT CHECK (estrato BETWEEN 1 AND 6),
  UNIQUE(ciudad_id, nombre)
);

-- 3. Campus universitarios
CREATE TABLE IF NOT EXISTS campus_universitarios (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ciudad_id BIGINT NOT NULL REFERENCES ciudades(id),
  institucion VARCHAR(150) NOT NULL,
  nombre_sede VARCHAR(150) NOT NULL,
  direccion VARCHAR(200) NOT NULL,
  latitud DECIMAL(10,7) NOT NULL CHECK (latitud BETWEEN -90 AND 90),
  longitud DECIMAL(10,7) NOT NULL CHECK (longitud BETWEEN -180 AND 180),
  activo BOOLEAN NOT NULL DEFAULT TRUE,
  UNIQUE(institucion, nombre_sede)
);

-- 4. Usuarios (ARRENDADOR, ADMIN) - estudiante es anónimo
CREATE TABLE IF NOT EXISTS usuarios (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre_completo VARCHAR(150) NOT NULL,
  email VARCHAR(180) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  telefono_whatsapp VARCHAR(20) NOT NULL,
  rol VARCHAR(20) NOT NULL CHECK (rol IN ('ARRENDADOR','ADMIN')),
  telefono_verificado BOOLEAN NOT NULL DEFAULT FALSE,
  creado_en TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 5. Servicios catálogo
CREATE TABLE IF NOT EXISTS servicios_catalogo (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre VARCHAR(80) NOT NULL UNIQUE,
  categoria VARCHAR(50) NOT NULL
);

-- 6. Publicaciones (oferta central) - FIX lat/lng + indice_confianza
CREATE TABLE IF NOT EXISTS publicaciones (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  usuario_id BIGINT NOT NULL REFERENCES usuarios(id),
  zona_barrio_id BIGINT NOT NULL REFERENCES zonas_barrios(id),
  titulo VARCHAR(150) NOT NULL CHECK (char_length(titulo) >= 10),
  descripcion TEXT NOT NULL CHECK (char_length(descripcion) >= 20),
  tipo_inmueble VARCHAR(30) NOT NULL CHECK (tipo_inmueble IN ('HABITACION_FAMILIAR','HABITACION_INDEPENDIENTE','APARTAESTUDIO','COMPARTIDO')),
  canon_mensual DECIMAL(10,2) NOT NULL CHECK (canon_mensual > 0),
  deposito_requerido DECIMAL(10,2) NOT NULL DEFAULT 0 CHECK (deposito_requerido >= 0),
  incluye_servicios_base BOOLEAN NOT NULL DEFAULT TRUE,
  reglas_convivencia TEXT NOT NULL CHECK (char_length(reglas_convivencia) >= 10),
  direccion_referencial VARCHAR(200) NOT NULL,
  latitud DECIMAL(10,7) CHECK (latitud BETWEEN -90 AND 90),
  longitud DECIMAL(10,7) CHECK (longitud BETWEEN -180 AND 180),
  estado VARCHAR(20) NOT NULL DEFAULT 'PENDIENTE' CHECK (estado IN ('PENDIENTE','ACTIVO','PAUSADO','ARRENDADO','EXPIRADO','RECHAZADO','DESACTIVADO')),
  indice_confianza SMALLINT NOT NULL DEFAULT 0 CHECK (indice_confianza BETWEEN 0 AND 100),
  fecha_publicacion TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  fecha_renovacion TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  fecha_expiracion TIMESTAMPTZ NOT NULL DEFAULT (NOW() + INTERVAL '30 days')
);
CREATE INDEX IF NOT EXISTS idx_publicaciones_estado_canon ON publicaciones(estado, canon_mensual);
CREATE INDEX IF NOT EXISTS idx_publicaciones_activo ON publicaciones(estado) WHERE estado='ACTIVO';

-- 7. Publicacion - Servicios (N-N)
CREATE TABLE IF NOT EXISTS publicacion_servicios (
  publicacion_id BIGINT NOT NULL REFERENCES publicaciones(id) ON DELETE CASCADE,
  servicio_id BIGINT NOT NULL REFERENCES servicios_catalogo(id),
  PRIMARY KEY (publicacion_id, servicio_id)
);

-- 8. Publicacion - Campus (N-N) con distancia Haversine precalculada
CREATE TABLE IF NOT EXISTS publicacion_campus (
  publicacion_id BIGINT NOT NULL REFERENCES publicaciones(id) ON DELETE CASCADE,
  campus_id BIGINT NOT NULL REFERENCES campus_universitarios(id),
  distancia_geodesica_m INTEGER NOT NULL CHECK (distancia_geodesica_m >= 0),
  PRIMARY KEY (publicacion_id, campus_id)
);
CREATE INDEX IF NOT EXISTS idx_pubcampus_campus_dist ON publicacion_campus(campus_id, distancia_geodesica_m);

-- 9. Imágenes
CREATE TABLE IF NOT EXISTS imagenes_publicacion (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  publicacion_id BIGINT NOT NULL REFERENCES publicaciones(id) ON DELETE CASCADE,
  url TEXT NOT NULL,
  orden SMALLINT NOT NULL CHECK (orden > 0),
  UNIQUE(publicacion_id, orden)
);

-- 10. Reportes (FIX estado PENDIENTE/DESCARTADO/CONFIRMADO, nunca ACTIVO)
CREATE TABLE IF NOT EXISTS reportes_publicacion (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  publicacion_id BIGINT NOT NULL REFERENCES publicaciones(id) ON DELETE CASCADE,
  usuario_id BIGINT REFERENCES usuarios(id),
  motivo VARCHAR(40) NOT NULL,
  detalle TEXT,
  estado VARCHAR(20) NOT NULL DEFAULT 'PENDIENTE' CHECK (estado IN ('PENDIENTE','DESCARTADO','CONFIRMADO')),
  fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_reportes_pub_estado ON reportes_publicacion(publicacion_id, estado);

-- 11. Auditoría máquina estados (faltante en doc original)
CREATE TABLE IF NOT EXISTS publicaciones_audit (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  publicacion_id BIGINT NOT NULL REFERENCES publicaciones(id) ON DELETE CASCADE,
  usuario_id BIGINT REFERENCES usuarios(id),
  evento VARCHAR(20) NOT NULL CHECK (evento IN ('CREATED','APPROVED','REJECTED','PAUSED','RESUMED','RENTED','EXPIRED','RENEWED','BLOCKED')),
  detalle TEXT,
  creado_en TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_audit_pub ON publicaciones_audit(publicacion_id, creado_en);

-- 12. Función Haversine (p26) - IMMUTABLE para índices
CREATE OR REPLACE FUNCTION haversine_m(lat1 DOUBLE PRECISION, lon1 DOUBLE PRECISION, lat2 DOUBLE PRECISION, lon2 DOUBLE PRECISION)
RETURNS INTEGER LANGUAGE plpgsql IMMUTABLE STRICT AS $$
DECLARE
  R CONSTANT DOUBLE PRECISION := 6371000;
  dlat DOUBLE PRECISION := radians(lat2-lat1);
  dlon DOUBLE PRECISION := radians(lon2-lon1);
  a DOUBLE PRECISION;
BEGIN
  a := sin(dlat/2)^2 + cos(radians(lat1))*cos(radians(lat2))*sin(dlon/2)^2;
  a := LEAST(1, GREATEST(0, a));
  RETURN (2*R*asin(sqrt(a)))::INTEGER;
END;
$$;

COMMIT;
