"""AlojaU - 005: admin automatizado (system_settings + estados extendidos).

Revision ID: 005_admin_automation
Revises: 004_pois_categoria

- Crea tabla system_settings (parámetros editables desde UI admin).
- Amplía chk_estado con PAUSADO_POR_REPORTE y REVISION_REQUERIDA (aditivo).
- Inserta defaults: dias_vigencia_publicacion=30,
  max_reportes_para_pausa_automatica=3, auto_aprobar_arrendadores_verificados=false.

Aplicar: alembic upgrade head (o pegar backend/db/005_admin_automation.sql en Supabase).
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

revision: str = '005_admin_automation'
down_revision: Union[str, None] = '004_pois_categoria'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute(sa.text("""
        CREATE TABLE IF NOT EXISTS system_settings (
          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          clave VARCHAR(80) NOT NULL UNIQUE,
          valor TEXT NOT NULL,
          tipo VARCHAR(20) NOT NULL DEFAULT 'int',
          descripcion TEXT,
          actualizado_en TIMESTAMPTZ NOT NULL DEFAULT NOW()
        )
    """))
    op.execute(sa.text("ALTER TABLE publicaciones DROP CONSTRAINT IF EXISTS chk_estado"))
    # Legado: BDs creadas con schema.sql previo traen el CHECK con nombre
    # automático; sin retirarlo, los estados nuevos siguen rechazados.
    op.execute(sa.text("ALTER TABLE publicaciones DROP CONSTRAINT IF EXISTS publicaciones_estado_check"))
    op.execute(sa.text("""
        ALTER TABLE publicaciones ADD CONSTRAINT chk_estado CHECK (
          estado IN ('PENDIENTE','ACTIVO','PAUSADO','ARRENDADO','EXPIRADO',
                     'RECHAZADO','DESACTIVADO','PAUSADO_POR_REPORTE','REVISION_REQUERIDA')
        )
    """))
    op.execute(sa.text("""
        INSERT INTO system_settings (clave, valor, tipo, descripcion) VALUES
          ('dias_vigencia_publicacion', '30', 'int', 'Días de vigencia al publicar/renovar'),
          ('max_reportes_para_pausa_automatica', '3', 'int', 'Reportes PENDIENTE/CONFIRMADO que pausan el aviso'),
          ('auto_aprobar_arrendadores_verificados', 'false', 'bool', 'Si true, PENDIENTE de verificados pasa a ACTIVO sin cola')
        ON CONFLICT (clave) DO NOTHING
    """))


def downgrade() -> None:
    op.execute(sa.text("DROP TABLE IF EXISTS system_settings"))
    op.execute(sa.text("ALTER TABLE publicaciones DROP CONSTRAINT IF EXISTS chk_estado"))
    op.execute(sa.text("""
        ALTER TABLE publicaciones ADD CONSTRAINT chk_estado CHECK (
          estado IN ('PENDIENTE','ACTIVO','PAUSADO','ARRENDADO','EXPIRADO','RECHAZADO','DESACTIVADO')
        )
    """))
