"""AlojaU - 007: enterprise auth (v13).

Revision ID: 007_auth_enterprise
Revises: 006_barrio_texto

Aditivo y seguro en free tier:
- usuarios: rol ESTUDIANTE base + futuros MODERADOR_CAMPUS/AUDITOR_LEGAL
  (CHECK reemplazado de forma aditiva), + auth_provider, supabase_id,
  email_verificado y auditoría Ley 1581 (acepto/fechas/ip/versión).
- Tablas nuevas: rate_limit_attempts, otp_codes, password_resets, sesiones.
- Todo IF NOT EXISTS para que schema.sql y migraciones converjan.

Aplicar: alembic upgrade head
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

revision: str = '007_auth_enterprise'
down_revision: Union[str, None] = '006_barrio_texto'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # 1) CHECK de rol aditivo (reemplaza el anterior sin romper filas).
    # Incluye el nombre autogenerado por Postgres en instalaciones antiguas.
    op.execute(sa.text("ALTER TABLE usuarios DROP CONSTRAINT IF EXISTS chk_rol"))
    op.execute(sa.text("ALTER TABLE usuarios DROP CONSTRAINT IF EXISTS usuarios_rol_check"))
    op.execute(sa.text(
        "ALTER TABLE usuarios ADD CONSTRAINT chk_rol "
        "CHECK (rol IN ('ESTUDIANTE','ARRENDADOR','ADMIN','MODERADOR_CAMPUS','AUDITOR_LEGAL'))"
    ))
    # 2) Columnas de identidad + Ley 1581.
    op.execute(sa.text(
        "ALTER TABLE usuarios ADD COLUMN IF NOT EXISTS auth_provider VARCHAR(30) "
        "NOT NULL DEFAULT 'password'"
    ))
    op.execute(sa.text(
        "ALTER TABLE usuarios ADD COLUMN IF NOT EXISTS supabase_id VARCHAR(64)"
    ))
    op.execute(sa.text(
        "ALTER TABLE usuarios ADD COLUMN IF NOT EXISTS email_verificado BOOLEAN "
        "NOT NULL DEFAULT FALSE"
    ))
    op.execute(sa.text(
        "ALTER TABLE usuarios ADD COLUMN IF NOT EXISTS acepto_tratamiento_datos BOOLEAN "
        "NOT NULL DEFAULT FALSE"
    ))
    op.execute(sa.text(
        "ALTER TABLE usuarios ADD COLUMN IF NOT EXISTS fecha_consentimiento TIMESTAMPTZ"
    ))
    op.execute(sa.text(
        "ALTER TABLE usuarios ADD COLUMN IF NOT EXISTS ip_consentimiento VARCHAR(45)"
    ))
    op.execute(sa.text(
        "ALTER TABLE usuarios ADD COLUMN IF NOT EXISTS version_politica VARCHAR(40)"
    ))
    op.execute(sa.text(
        "CREATE UNIQUE INDEX IF NOT EXISTS uq_usuarios_supabase_id "
        "ON usuarios(supabase_id) WHERE supabase_id IS NOT NULL"
    ))
    # 3) Rate-limit persistente (sobrevive reinicios Render).
    op.execute(sa.text(
        """CREATE TABLE IF NOT EXISTS rate_limit_attempts (
          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          clave VARCHAR(180) NOT NULL,
          exito BOOLEAN NOT NULL DEFAULT FALSE,
          creado_en TIMESTAMPTZ NOT NULL DEFAULT NOW()
        )"""
    ))
    op.execute(sa.text(
        "CREATE INDEX IF NOT EXISTS idx_ratelimit_clave_creado "
        "ON rate_limit_attempts(clave, creado_en)"
    ))
    # 4) OTP 6 dígitos (10 min).
    op.execute(sa.text(
        """CREATE TABLE IF NOT EXISTS otp_codes (
          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          email VARCHAR(180) NOT NULL,
          codigo_hash VARCHAR(255) NOT NULL,
          proposito VARCHAR(30) NOT NULL DEFAULT 'email_verify',
          consumido BOOLEAN NOT NULL DEFAULT FALSE,
          expira_en TIMESTAMPTZ NOT NULL,
          creado_en TIMESTAMPTZ NOT NULL DEFAULT NOW()
        )"""
    ))
    op.execute(sa.text(
        "CREATE INDEX IF NOT EXISTS idx_otp_email_creado ON otp_codes(email, creado_en)"
    ))
    # 5) Recovery un solo uso (15 min).
    op.execute(sa.text(
        """CREATE TABLE IF NOT EXISTS password_resets (
          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          email VARCHAR(180) NOT NULL,
          token_hash VARCHAR(255) NOT NULL,
          consumido BOOLEAN NOT NULL DEFAULT FALSE,
          expira_en TIMESTAMPTZ NOT NULL,
          creado_en TIMESTAMPTZ NOT NULL DEFAULT NOW(),
          CONSTRAINT uq_pwreset_token UNIQUE (token_hash)
        )"""
    ))
    op.execute(sa.text(
        "CREATE INDEX IF NOT EXISTS idx_pwreset_email_creado "
        "ON password_resets(email, creado_en)"
    ))
    # 6) Sesiones para revocación global.
    op.execute(sa.text(
        """CREATE TABLE IF NOT EXISTS sesiones (
          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          usuario_id BIGINT NOT NULL REFERENCES usuarios(id) ON DELETE CASCADE,
          jti VARCHAR(64) NOT NULL,
          ip VARCHAR(45),
          user_agent VARCHAR(255),
          revocado BOOLEAN NOT NULL DEFAULT FALSE,
          creado_en TIMESTAMPTZ NOT NULL DEFAULT NOW(),
          revocado_en TIMESTAMPTZ,
          CONSTRAINT uq_sesiones_jti UNIQUE (jti)
        )"""
    ))
    op.execute(sa.text(
        "CREATE INDEX IF NOT EXISTS idx_sesiones_usuario ON sesiones(usuario_id)"
    ))


def downgrade() -> None:
    op.execute(sa.text("DROP TABLE IF EXISTS sesiones"))
    op.execute(sa.text("DROP TABLE IF EXISTS password_resets"))
    op.execute(sa.text("DROP TABLE IF EXISTS otp_codes"))
    op.execute(sa.text("DROP TABLE IF EXISTS rate_limit_attempts"))
    op.execute(sa.text("DROP INDEX IF EXISTS uq_usuarios_supabase_id"))
    for col in ("version_politica", "ip_consentimiento", "fecha_consentimiento",
                "acepto_tratamiento_datos", "email_verificado", "supabase_id",
                "auth_provider"):
        op.execute(sa.text(f"ALTER TABLE usuarios DROP COLUMN IF EXISTS {col}"))
    op.execute(sa.text("ALTER TABLE usuarios DROP CONSTRAINT IF EXISTS chk_rol"))
    op.execute(sa.text(
        "ALTER TABLE usuarios ADD CONSTRAINT chk_rol "
        "CHECK (rol IN ('ARRENDADOR','ADMIN'))"
    ))
