"""AlojaU - 011: métrica de vistas (v15.2).

Revision ID: 011_metrica_vistas
Revises: 010_fk_cascade_and_sequences

- publicaciones.vistas INTEGER NOT NULL DEFAULT 0.
- vistas_dedup(publicacion_id, marca, dia) con UNIQUE(pub, marca) para
  dedup diaria por IP hasheada (nunca la IP en claro).
Aditivo e idempotente. Aplicar: alembic upgrade head o el espejo SQL.
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

revision: str = '011_metrica_vistas'
down_revision: Union[str, None] = '010_fk_cascade_and_sequences'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute(sa.text(
        "ALTER TABLE publicaciones ADD COLUMN IF NOT EXISTS vistas INTEGER "
        "NOT NULL DEFAULT 0"
    ))
    op.execute(sa.text(
        """CREATE TABLE IF NOT EXISTS vistas_dedup (
          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          publicacion_id BIGINT NOT NULL,
          marca VARCHAR(64) NOT NULL,
          dia VARCHAR(10) NOT NULL,
          creado_en TIMESTAMPTZ NOT NULL DEFAULT NOW(),
          CONSTRAINT uq_vista_pub_marca UNIQUE (publicacion_id, marca)
        )"""
    ))
    op.execute(sa.text(
        "CREATE INDEX IF NOT EXISTS idx_vistas_dedup_dia ON vistas_dedup(dia)"
    ))


def downgrade() -> None:
    op.execute(sa.text("DROP TABLE IF EXISTS vistas_dedup"))
    op.execute(sa.text("ALTER TABLE publicaciones DROP COLUMN IF EXISTS vistas"))
