"""AlojaU - 019: notificaciones in-app + búsquedas guardadas (Fase 1).

Revision ID: 019_notificaciones_y_busquedas
Revises: 018_telegram_contacto

- busquedas_guardadas: alertas del estudiante ("avísame arriendos $X-Y cerca
  a campus Z"). FKs reales con ON DELETE SET NULL (campus_universitarios,
  zonas_barrios); índice compuesto idx_bg_matching(activa, campus_id, tipo)
  parcial WHERE activa para el matching engine.
- notificaciones: bandeja única de la campanita. Dedupe por evento_id
  (UNIQUE usuario+evento): reintentos seguros sin prohibir repeticiones
  futuras del mismo tipo. canal='app' hoy (reserva multicanal, costo cero).
- Aditiva e idempotente (IF NOT EXISTS). Downgrade simétrico.
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

revision: str = '019_notificaciones_y_busquedas'
down_revision: Union[str, None] = '018_telegram_contacto'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute(sa.text(
        "CREATE TABLE IF NOT EXISTS busquedas_guardadas ("
        "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
        "usuario_id BIGINT NOT NULL REFERENCES usuarios(id) ON DELETE CASCADE, "
        "nombre TEXT NULL, "
        "precio_min NUMERIC NULL CHECK (precio_min >= 0), "
        "precio_max NUMERIC NULL CHECK (precio_max >= 0), "
        "campus_id BIGINT NULL REFERENCES campus_universitarios(id) ON DELETE SET NULL, "
        "zona_barrio_id BIGINT NULL REFERENCES zonas_barrios(id) ON DELETE SET NULL, "
        "tipo TEXT NULL, "
        "servicios_ids INT[] NOT NULL DEFAULT '{}', "
        "activa BOOLEAN NOT NULL DEFAULT TRUE, "
        "created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), "
        "CONSTRAINT chk_bg_rango CHECK "
        "(precio_min IS NULL OR precio_max IS NULL OR precio_min <= precio_max)"
        ")"
    ))
    op.execute(sa.text(
        "CREATE INDEX IF NOT EXISTS idx_bg_matching "
        "ON busquedas_guardadas(activa, campus_id, tipo) WHERE activa"
    ))
    op.execute(sa.text(
        "CREATE TABLE IF NOT EXISTS notificaciones ("
        "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
        "usuario_id BIGINT NOT NULL REFERENCES usuarios(id) ON DELETE CASCADE, "
        "publicacion_id BIGINT NULL REFERENCES publicaciones(id) ON DELETE CASCADE, "
        "busqueda_id BIGINT NULL REFERENCES busquedas_guardadas(id) ON DELETE SET NULL, "
        "evento_id TEXT NOT NULL, "
        "tipo TEXT NOT NULL CHECK (tipo IN ('nuevo_arriendo','moderacion','vencimiento')), "
        "titulo TEXT NOT NULL, "
        "cuerpo TEXT NOT NULL DEFAULT '', "
        "canal TEXT NOT NULL DEFAULT 'app', "
        "leida BOOLEAN NOT NULL DEFAULT FALSE, "
        "leida_en TIMESTAMPTZ NULL, "
        "created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), "
        "CONSTRAINT uq_notif_usuario_evento UNIQUE (usuario_id, evento_id)"
        ")"
    ))
    op.execute(sa.text(
        "CREATE INDEX IF NOT EXISTS idx_notif_bandeja "
        "ON notificaciones(usuario_id, created_at DESC)"
    ))
    op.execute(sa.text(
        "CREATE INDEX IF NOT EXISTS idx_notif_noleidas "
        "ON notificaciones(usuario_id) WHERE leida IS FALSE"
    ))


def downgrade() -> None:
    op.execute(sa.text("DROP INDEX IF EXISTS idx_notif_noleidas"))
    op.execute(sa.text("DROP INDEX IF EXISTS idx_notif_bandeja"))
    op.execute(sa.text("DROP TABLE IF EXISTS notificaciones"))
    op.execute(sa.text("DROP INDEX IF EXISTS idx_bg_matching"))
    op.execute(sa.text("DROP TABLE IF EXISTS busquedas_guardadas"))
