-- =============================================================================
-- AlojaU - 005_fix_estado_and_campus (migración Supabase producción)
-- Archivo: backend/db/migrations/005_fix_estado_and_campus.sql
-- Ejecutar en: Supabase Dashboard -> SQL Editor -> New query -> pegar -> Run.
-- Equivale a alembic 003 + 004 + 005 (consolidado).
--
-- QUÉ HACE (todo idempotente, sin datos ficticios):
--   1. Extensiones pg_trgm + unaccent e índices FTS/trigramas (búsqueda).
--   2. Columna campus_universitarios.categoria + CHECK + índice ("campus").
--   3. Función haversine_m + trigger de distancias (004).
--   4. Tabla system_settings + defaults (005).
--   5. CHECK de estados con PAUSADO_POR_REPORTE y REVISION_REQUERIDA ("estado"):
--      retira chk_estado Y el legado publicaciones_estado_check (nombre
--      automático de schema.sql previo) y recrea uno solo de 9 estados.
--
-- COMPATIBILIDAD: corre igual sobre BD limpia (con schema.sql aplicado) o
-- existente. NO hace TRUNCATE ni INSERT de demo: los datos reales de prod
-- quedan intactos. Si algún aviso violara el CHECK nuevo, el ALTER fallaría
-- sin cambiar nada (transaccional): revisar esos estados antes de reintentar.
-- Tiempo estimado: segundos. Lock breve de escritura en CREATE INDEX
-- (sin CONCURRENTLY); preferir horario valle.
-- =============================================================================
BEGIN;

-- 1. Búsqueda por texto -------------------------------------------------------
CREATE EXTENSION IF NOT EXISTS pg_trgm;
CREATE EXTENSION IF NOT EXISTS unaccent;

CREATE INDEX IF NOT EXISTS idx_publicaciones_fts ON publicaciones
USING gin(to_tsvector('spanish', coalesce(titulo, '') || ' ' || coalesce(descripcion, '')));

CREATE INDEX IF NOT EXISTS idx_publicaciones_trgm ON publicaciones
USING gin(titulo gin_trgm_ops);

-- 2. Lugares por categoría ("campus") -----------------------------------------
ALTER TABLE campus_universitarios
  ADD COLUMN IF NOT EXISTS categoria VARCHAR(50) NOT NULL DEFAULT 'UNIVERSIDAD';

DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'chk_campus_categoria') THEN
    ALTER TABLE campus_universitarios
      ADD CONSTRAINT chk_campus_categoria
      CHECK (categoria IN ('UNIVERSIDAD','CENTRO_COMERCIAL','SALUD','TRANSPORTE','OTRO'));
  END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_campus_ciudad_categoria
  ON campus_universitarios(ciudad_id, categoria);

-- 3. Haversine + trigger de distancias ----------------------------------------
CREATE OR REPLACE FUNCTION haversine_m(
    lat1 DOUBLE PRECISION, lon1 DOUBLE PRECISION,
    lat2 DOUBLE PRECISION, lon2 DOUBLE PRECISION
) RETURNS INTEGER
LANGUAGE plpgsql IMMUTABLE STRICT
AS $$
DECLARE
    R CONSTANT DOUBLE PRECISION := 6371000;
    dlat DOUBLE PRECISION := radians(lat2 - lat1);
    dlon DOUBLE PRECISION := radians(lon2 - lon1);
    a DOUBLE PRECISION;
BEGIN
    a := sin(dlat/2)^2 + cos(radians(lat1)) * cos(radians(lat2)) * sin(dlon/2)^2;
    a := LEAST(1, GREATEST(0, a));
    RETURN (2 * R * asin(sqrt(a)))::INTEGER;
END;
$$;

CREATE OR REPLACE FUNCTION trg_fn_publicacion_recalcular_distancias()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  IF NEW.latitud IS NULL OR NEW.longitud IS NULL THEN
    UPDATE publicacion_campus
       SET distancia_geodesica_m = NULL
     WHERE publicacion_id = NEW.id;
    RETURN NEW;
  END IF;
  INSERT INTO publicacion_campus (publicacion_id, campus_id, distancia_geodesica_m)
  SELECT NEW.id, c.id,
         haversine_m(NEW.latitud, NEW.longitud, c.latitud, c.longitud)
    FROM campus_universitarios c
    JOIN zonas_barrios z ON z.ciudad_id = c.ciudad_id
    JOIN publicaciones p ON p.id = NEW.id AND p.zona_barrio_id = z.id
   WHERE c.activo = TRUE
  ON CONFLICT (publicacion_id, campus_id)
  DO UPDATE SET distancia_geodesica_m = EXCLUDED.distancia_geodesica_m;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_publicacion_recalcular_distancias ON publicaciones;
CREATE TRIGGER trg_publicacion_recalcular_distancias
AFTER INSERT OR UPDATE OF latitud, longitud ON publicaciones
FOR EACH ROW EXECUTE FUNCTION trg_fn_publicacion_recalcular_distancias();

-- 4. Ajustes del sistema -------------------------------------------------------
CREATE TABLE IF NOT EXISTS system_settings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  clave VARCHAR(80) NOT NULL UNIQUE,
  valor TEXT NOT NULL,
  tipo VARCHAR(20) NOT NULL DEFAULT 'int',
  descripcion TEXT,
  actualizado_en TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

INSERT INTO system_settings (clave, valor, tipo, descripcion) VALUES
  ('dias_vigencia_publicacion', '30', 'int', 'Días de vigencia al publicar/renovar'),
  ('max_reportes_para_pausa_automatica', '3', 'int', 'Reportes PENDIENTE/CONFIRMADO que pausan el aviso'),
  ('auto_aprobar_arrendadores_verificados', 'false', 'bool', 'Si true, PENDIENTE de verificados pasa a ACTIVO sin cola')
ON CONFLICT (clave) DO NOTHING;

-- 5. Estados extendidos ("estado") ---------------------------------------------
ALTER TABLE publicaciones DROP CONSTRAINT IF EXISTS chk_estado;
ALTER TABLE publicaciones DROP CONSTRAINT IF EXISTS publicaciones_estado_check;
ALTER TABLE publicaciones ADD CONSTRAINT chk_estado CHECK (
  estado IN ('PENDIENTE','ACTIVO','PAUSADO','ARRENDADO','EXPIRADO',
             'RECHAZADO','DESACTIVADO','PAUSADO_POR_REPORTE','REVISION_REQUERIDA')
);

COMMIT;

-- Verificación (ejecutar después, fuera de la transacción):
-- SELECT conname FROM pg_constraint WHERE conrelid = 'publicaciones'::regclass AND conname LIKE '%estado%';
--   -> solo chk_estado
-- SELECT indexname FROM pg_indexes WHERE tablename IN ('publicaciones','campus_universitarios');
--   -> idx_publicaciones_fts, idx_publicaciones_trgm, idx_campus_ciudad_categoria
-- SELECT clave, valor FROM system_settings;
--   -> 3 filas
