-- AlojaU - 007: enterprise auth (v13). Espejo SQL de alembic 007_auth_enterprise.
-- Aditivo e idempotente (IF NOT EXISTS). Aplicar: psql $DATABASE_URL -f 007_auth_enterprise.sql
BEGIN;

ALTER TABLE usuarios DROP CONSTRAINT IF EXISTS chk_rol;
-- Nombre autogenerado por Postgres en instalaciones antiguas (sin nombre explícito).
ALTER TABLE usuarios DROP CONSTRAINT IF EXISTS usuarios_rol_check;
ALTER TABLE usuarios ADD CONSTRAINT chk_rol
  CHECK (rol IN ('ESTUDIANTE','ARRENDADOR','ADMIN','MODERADOR_CAMPUS','AUDITOR_LEGAL'));

ALTER TABLE usuarios ADD COLUMN IF NOT EXISTS auth_provider VARCHAR(30)
  NOT NULL DEFAULT 'password';
ALTER TABLE usuarios ADD COLUMN IF NOT EXISTS supabase_id VARCHAR(64);
ALTER TABLE usuarios ADD COLUMN IF NOT EXISTS email_verificado BOOLEAN
  NOT NULL DEFAULT FALSE;
ALTER TABLE usuarios ADD COLUMN IF NOT EXISTS acepto_tratamiento_datos BOOLEAN
  NOT NULL DEFAULT FALSE;
ALTER TABLE usuarios ADD COLUMN IF NOT EXISTS fecha_consentimiento TIMESTAMPTZ;
ALTER TABLE usuarios ADD COLUMN IF NOT EXISTS ip_consentimiento VARCHAR(45);
ALTER TABLE usuarios ADD COLUMN IF NOT EXISTS version_politica VARCHAR(40);
CREATE UNIQUE INDEX IF NOT EXISTS uq_usuarios_supabase_id
  ON usuarios(supabase_id) WHERE supabase_id IS NOT NULL;

CREATE TABLE IF NOT EXISTS rate_limit_attempts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  clave VARCHAR(180) NOT NULL,
  exito BOOLEAN NOT NULL DEFAULT FALSE,
  creado_en TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_ratelimit_clave_creado
  ON rate_limit_attempts(clave, creado_en);

CREATE TABLE IF NOT EXISTS otp_codes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email VARCHAR(180) NOT NULL,
  codigo_hash VARCHAR(255) NOT NULL,
  proposito VARCHAR(30) NOT NULL DEFAULT 'email_verify',
  consumido BOOLEAN NOT NULL DEFAULT FALSE,
  expira_en TIMESTAMPTZ NOT NULL,
  creado_en TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_otp_email_creado ON otp_codes(email, creado_en);

CREATE TABLE IF NOT EXISTS password_resets (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email VARCHAR(180) NOT NULL,
  token_hash VARCHAR(255) NOT NULL,
  consumido BOOLEAN NOT NULL DEFAULT FALSE,
  expira_en TIMESTAMPTZ NOT NULL,
  creado_en TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT uq_pwreset_token UNIQUE (token_hash)
);
CREATE INDEX IF NOT EXISTS idx_pwreset_email_creado
  ON password_resets(email, creado_en);

CREATE TABLE IF NOT EXISTS sesiones (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  usuario_id BIGINT NOT NULL REFERENCES usuarios(id) ON DELETE CASCADE,
  jti VARCHAR(64) NOT NULL,
  ip VARCHAR(45),
  user_agent VARCHAR(255),
  revocado BOOLEAN NOT NULL DEFAULT FALSE,
  creado_en TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  revocado_en TIMESTAMPTZ,
  CONSTRAINT uq_sesiones_jti UNIQUE (jti)
);
CREATE INDEX IF NOT EXISTS idx_sesiones_usuario ON sesiones(usuario_id);

COMMIT;
