-- AlojaU - 011: métrica de vistas (v15.2). Espejo SQL de alembic 011.
-- Aditivo e idempotente (IF NOT EXISTS). Aplicar: psql $DATABASE_URL -f 011_metrica_vistas.sql
BEGIN;

ALTER TABLE publicaciones ADD COLUMN IF NOT EXISTS vistas INTEGER
  NOT NULL DEFAULT 0;

CREATE TABLE IF NOT EXISTS vistas_dedup (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  publicacion_id BIGINT NOT NULL,
  marca VARCHAR(64) NOT NULL,
  dia VARCHAR(10) NOT NULL,
  creado_en TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT uq_vista_pub_marca UNIQUE (publicacion_id, marca)
);
CREATE INDEX IF NOT EXISTS idx_vistas_dedup_dia ON vistas_dedup(dia);

COMMIT;
