-- 019 notificaciones in-app + búsquedas guardadas (Fase 1).
-- Espejo manual de backend/alembic/versions/019_notificaciones_y_busquedas.py
-- para aplicar en Supabase (SQL Editor). Idempotente. Ver downgrade al final.
-- Fase 2 usará: matcher con servicios @>, enqueue con savepoint + evento_id,
-- purga TTL 90d en escritura (jamás en GET).

-- UPGRADE ----------------------------------------------------------------
CREATE TABLE IF NOT EXISTS busquedas_guardadas (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  usuario_id BIGINT NOT NULL REFERENCES usuarios(id) ON DELETE CASCADE,
  nombre TEXT NULL,
  precio_min NUMERIC NULL CHECK (precio_min >= 0),
  precio_max NUMERIC NULL CHECK (precio_max >= 0),
  campus_id BIGINT NULL REFERENCES campus_universitarios(id) ON DELETE SET NULL,
  zona_barrio_id BIGINT NULL REFERENCES zonas_barrios(id) ON DELETE SET NULL,
  tipo TEXT NULL,
  servicios_ids INT[] NOT NULL DEFAULT '{}',
  activa BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT chk_bg_rango CHECK (precio_min IS NULL OR precio_max IS NULL OR precio_min <= precio_max)
);
CREATE INDEX IF NOT EXISTS idx_bg_matching
  ON busquedas_guardadas(activa, campus_id, tipo) WHERE activa;

CREATE TABLE IF NOT EXISTS notificaciones (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  usuario_id BIGINT NOT NULL REFERENCES usuarios(id) ON DELETE CASCADE,
  publicacion_id BIGINT NULL REFERENCES publicaciones(id) ON DELETE CASCADE,
  busqueda_id BIGINT NULL REFERENCES busquedas_guardadas(id) ON DELETE SET NULL,
  evento_id TEXT NOT NULL,
  tipo TEXT NOT NULL CONSTRAINT chk_notif_tipo CHECK (tipo IN ('nuevo_arriendo','moderacion','vencimiento')),
  titulo TEXT NOT NULL,
  cuerpo TEXT NOT NULL DEFAULT '',
  canal TEXT NOT NULL DEFAULT 'app',
  leida BOOLEAN NOT NULL DEFAULT FALSE,
  leida_en TIMESTAMPTZ NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT uq_notif_usuario_evento UNIQUE (usuario_id, evento_id)
);
CREATE INDEX IF NOT EXISTS idx_notif_bandeja ON notificaciones(usuario_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_notif_noleidas ON notificaciones(usuario_id) WHERE leida IS FALSE;

-- DOWNGRADE (revertir Fase 1; no toca el resto del esquema) ----------------
-- DROP INDEX IF EXISTS idx_notif_noleidas;
-- DROP INDEX IF EXISTS idx_notif_bandeja;
-- DROP TABLE IF EXISTS notificaciones;
-- DROP INDEX IF EXISTS idx_bg_matching;
-- DROP TABLE IF EXISTS busquedas_guardadas;
